microarch_level:
  - 1
  - 3  # [unix and x86_64]
  - 4  # [unix and x86_64]

github_actions_labels:                # [unix]
- blacksmith-16vcpu-ubuntu-2404       # [linux64]
- blacksmith-16vcpu-ubuntu-2404-arm   # [linux and aarch64]
- blacksmith-12vcpu-macos-latest      # [osx]

c_compiler:             # [osx]
  - clang               # [osx]
cxx_compiler:           # [osx]
  - clangxx             # [osx]
cxx_compiler_version:   # [osx]
  - 22                  # [osx]

libboost_devel:
- "1.91"
libboost_headers:
- "1.91"
libboost_python_devel:
- "1.91"
