{% set version = "2.38" %}
{% set sha1 = "79d423efe7195f5940d5e7f7dcea19cc06a031b9" %}

package:
  name: graph-tool
  version: {{ version }}

source:
  fn: graph-tool-{{ version }}.tar.bz2
  url: https://downloads.skewed.de/graph-tool/graph-tool-{{ version }}.tar.bz2
  sha1: {{ sha1 }}

  patches:
    # Don't let configure test the python configuration via a test module;
    # it fails to link because we don't include -lpython in LDFLAGS.
    - patches/no-check-python-link.patch

    # Don't use autotools to detect and test boost-python.
    - patches/skip-boost-python-config.patch

    # In v2.38, src/graph/inference/Makefile.am is missing some files
    - patches/add-missing-inference-support-headers.patch

build:
  skip: true  # [win]
  number: 0
  detect_binary_files_with_prefix: true

  # conda-build 3.18.12 uses LIEF instead of patchelf,
  # which may be causing problems for this recipe.
  # We can force it to use patchelf with this setting.
  # There might be other bugs related to LIEF, too:
  # - https://github.com/conda-forge/staged-recipes/pull/10979#issuecomment-595388237
  # - https://github.com/lief-project/LIEF/issues/239
  # 
  # (Maybe this setting won't be needed in a later version of conda-build.)
  rpaths_patcher: patchelf  # [linux]

requirements:
  build:
    - libtool
    - autoconf
    - automake
    - pkg-config
    - {{ compiler("cxx") }}
    - llvm-openmp           # [osx]
  host:
    - python
    - numpy
    - boost-cpp
    - boost
    - expat
    - scipy >=1.0
    - gmp
    - cgal-cpp 5.0*
    - sparsehash 2.0*
    - cairomm
    - pycairo
    - glib
  run:
    - python
    - llvm-openmp  # [osx]
    - boost-cpp
    - boost
    - expat
    - scipy >=1.0
    - {{ pin_compatible('numpy') }}
    - gmp
    - sparsehash >=2.0
    - cairomm
    - pycairo
    - gdk-pixbuf
    - librsvg
    - gtk3
    - pygobject
    - matplotlib-base
    - zstandard

test:
  imports:
    - graph_tool
    - graph_tool.all
    - graph_tool.draw
    - graph_tool.draw.cairo_draw

about:
  home: https://graph-tool.skewed.de/
  summary: Efficient network analysis
  license: LGPL-3.0-or-later
  license_file:
    - licenses/LICENSE
    - licenses/LICENSE.LESSER
    - licenses/pcg-cpp/LICENSE-APACHE.txt
    - licenses/pcg-cpp/LICENSE-MIT.txt

extra:
  recipe-maintainers:
    - stuarteberg
    - ostrokach
    - count0
