{% set version = "2.45" %}
{% set sha1 = "861178fbbb96d05ffc7231d3dcee21263f63a06d" %}

package:
  name: graph-tool-suite
  version: {{ version }}

source:
  fn: graph-tool-{{ version }}.tar.bz2
  url: https://downloads.skewed.de/graph-tool/graph-tool-{{ version }}.tar.bz2
  sha1: {{ sha1 }}

  patches:
    # Don't let configure test the python configuration via a test module;
    # it fails to link because we don't include -lpython in LDFLAGS.
    - patches/no-check-python-link.patch

    # Don't use autotools to detect and test boost-python.
    - patches/skip-boost-python-config.patch

    # When cross-compiling, don't let configure run a CGAL test program.
    # Just trust the location we pass via --with-cgal
    - patches/skip-cgal-check.patch  # [build_platform != target_platform]

build:
  skip: true  # [win]
  number: 3
  detect_binary_files_with_prefix: true

  # conda-build 3.18.12 uses LIEF instead of patchelf,
  # which may be causing problems for this recipe.
  # We can force it to use patchelf with this setting.
  # There might be other bugs related to LIEF, too:
  # - https://github.com/conda-forge/staged-recipes/pull/10979#issuecomment-595388237
  # - https://github.com/lief-project/LIEF/issues/239
  # 
  # (Maybe this setting won't be needed in a later version of conda-build.)
  rpaths_patcher: patchelf  # [linux]

outputs:
  - name: graph-tool-base
    script: build_base.sh
    build:
      ignore_run_exports_from:
        - pycairo
        - cairomm
        - glib
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pycairo                                # [build_platform != target_platform]
        - make
        - libtool
        - autoconf
        - automake
        - gnuconfig
        - pkg-config
        - {{ compiler("cxx") }}
        - llvm-openmp           # [osx]
      host:
        - python
        - numpy
        - boost-cpp
        - boost
        - expat
        - scipy >=1.0
        - gmp
        - cgal-cpp 5.5*
        - sparsehash 2.0*
        - cairomm
        - pycairo
        - glib
      run:
        - python
        - llvm-openmp  # [osx]
        - boost-cpp
        - boost
        - expat
        - scipy >=1.0
        - {{ pin_compatible('numpy') }}
        - gmp
        - sparsehash >=2.0
        - zstandard
    test:
      files:
        - test_base_deps.sh
        - test_base_imports.py
      commands:
        - bash test_base_deps.sh
        - python test_base_imports.py

  - name: graph-tool
    requirements:
      host:
        # Although there's no "build" for this subpackage per se,
        # I think we might need to list these build-time dependencies here
        # to ensure that the runtime dependencies are properly pinned.
        - python
        - cairomm
        - pycairo
        - glib
      run:
        - python
        - {{ pin_subpackage('graph-tool-base', exact=True) }}
        - cairomm
        - pycairo
        - gdk-pixbuf
        - librsvg
        - gtk3
        - pygobject
        - matplotlib-base
    test:
      files:
        - test_all_imports.py
      commands:
        - python test_all_imports.py

about:
  home: https://graph-tool.skewed.de/
  summary: |
    Graph-tool is an efficient Python module for manipulation and statistical analysis of graphs (a.k.a. networks).
    The 'graph-tool' conda package installs graph-tool and all dependencies, including drawing dependencies.
    For users who don't need drawing support, the 'graph-tool-base' conda package installs graph-tool and
    only essential dependencies (but none for drawing).

  license: LGPL-3.0-or-later
  license_file:
    - licenses/LICENSE
    - licenses/LICENSE.LESSER
    - licenses/pcg-cpp/LICENSE-APACHE.txt
    - licenses/pcg-cpp/LICENSE-MIT.txt

extra:
  recipe-maintainers:
    - stuarteberg
    - ostrokach
    - count0
