{% set version = "2.72" %}
{% set sha1 = "0fe903dd04146b9021c37f1b35e6ca3b2d68d2fc" %}
{% set build = 1 %}

package:
  name: graph-tool-suite
  version: {{ version }}

source:
  fn: graph-tool-{{ version }}.tar.bz2
  url: https://downloads.skewed.de/graph-tool/graph-tool-{{ version }}.tar.bz2
  sha1: {{ sha1 }}

  patches:
    # Don't let configure test the python configuration via a test module;
    # it fails to link because we don't include -lpython in LDFLAGS.
    - patches/no-check-python-link.patch

    # Don't use autotools to detect and test boost-python.
    - patches/skip-boost-python-config.patch

    # When cross-compiling, don't let configure run a CGAL test program.
    # Just trust the location we pass via --with-cgal
    #- patches/skip-cgal-check.patch  # [build_platform != target_platform]
    - patches/skip-cgal-check.patch

build:
  skip: true  # [win]
  number: {{ build }}  # [not (unix and x86_64)]
  number: {{ build + 100 }}  # [unix and x86_64 and microarch_level == 1]
  number: {{ build + 300 }}  # [unix and x86_64 and microarch_level == 3]
  number: {{ build + 400 }}  # [unix and x86_64 and microarch_level == 4]
  detect_binary_files_with_prefix: true

  # conda-build 3.18.12 uses LIEF instead of patchelf,
  # which may be causing problems for this recipe.
  # We can force it to use patchelf with this setting.
  # There might be other bugs related to LIEF, too:
  # - https://github.com/conda-forge/staged-recipes/pull/10979#issuecomment-595388237
  # - https://github.com/lief-project/LIEF/issues/239
  # 
  # (Maybe this setting won't be needed in a later version of conda-build.)
  rpaths_patcher: patchelf  # [linux]

outputs:
  - name: graph-tool-base
    script: build_base.sh
    build:
      # In the 'graph-tool-base' package ignore run_exports for drawing dependencies,
      # but respect them in the 'graph-tool' package (see below).
      ignore_run_exports_from:
        - pycairo
        - cairomm-1.16
        - glib
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pycairo                                # [build_platform != target_platform]
        - make
        - libtool
        - autoconf
        - automake
        - gnuconfig
        - pkg-config
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - llvm-openmp           # [osx]
        - x86_64-microarch-level {{ microarch_level }}  # [unix and x86_64 and microarch_level < 4]
      host:
        - python
        - setuptools
        - numpy
        - libboost-devel
        - libboost-python-devel
        - expat
        - scipy >=1.0
        - gmp
        - cgal-cpp 5.6*
        - sparsehash 2.0*
        - cairomm-1.16
        - pycairo
        - glib
      run:
        - python
        - llvm-openmp  # [osx]
        - expat
        - scipy >=1.0
        - gmp
        - sparsehash >=2.0
        - zstandard
        - _x86_64-microarch-level {{ microarch_level }}  # [unix and x86_64 and microarch_level == 4]

    test:
      files:
        - test_base_deps.sh            # [microarch_level < 4]
        - test_base_imports.py         # [microarch_level < 4]
      commands:
        - bash test_base_deps.sh       # [microarch_level < 4]
        - python test_base_imports.py  # [microarch_level < 4]

  - name: graph-tool
    requirements:
      host:
        # Although there's no "build" for this subpackage per se,
        # I think we might need to list these build-time dependencies here
        # to ensure that the runtime dependencies are properly pinned.
        - python
        - cairomm-1.16
        - pycairo
        - glib
      run:
        - python
        - {{ pin_subpackage('graph-tool-base', exact=True) }}
        - cairomm-1.16
        - pycairo
        - gdk-pixbuf
        - librsvg
        - gtk3
        - pygobject
        - matplotlib-base
    test:
      files:
        - test_all_imports.py         # [microarch_level < 4]
      commands:
        - python test_all_imports.py  # [microarch_level < 4]

about:
  home: https://graph-tool.skewed.de/
  summary: |
    Graph-tool is an efficient Python module for manipulation and statistical analysis of graphs (a.k.a. networks).
    The 'graph-tool' conda package installs graph-tool and all dependencies, including drawing dependencies.
    For users who don't need drawing support, the 'graph-tool-base' conda package installs graph-tool and
    only essential dependencies (but none for drawing).

  license: LGPL-3.0-or-later
  license_file:
    - licenses/LICENSE
    - licenses/LICENSE.LESSER
    - licenses/pcg-cpp/LICENSE-APACHE.txt
    - licenses/pcg-cpp/LICENSE-MIT.txt

extra:
  recipe-maintainers:
    - stuarteberg
    - ostrokach
    - count0
