travis:
  secure:
    BINSTAR_TOKEN: GayiOmzAPptBXbqmDd89+D4HnUHPxRjDEungkdxAyaEq00hXHUwdCKnYPUmdJiNJ6yY5u/BObb6K69tZ6eZYamC3n0fEa+//libugezPRPParpGnHoPHlqHsNIA7jfHvL8FCPy15OSATah7VlNkgXcdPVdhcMy+Z+pikTOk0bTZr9zIZ+5l4s/cnh600VjB5vOH9qL02wG3uDLkRf3lTGcZcbsZcrJ8nBOF/I6pEM7WesdQOYZzNOOqStJ0XyCwua7kSeGShIbi+2R+RmLL2dsJa+Y5f6WDMSh8Woz0OnW2LunYPIW9CFkIDobONJF2aEB3n0ljLiIm7yhmErS4F2+c78n76qwg1t2W+0iYcBmG2O+tC+b6nkIq4nQe0UDKah0ciOY8DZehKj+fxTDP1rgs0JUyrECFQupslYeZuhWTUJnJDBLJmoKoVLLvefQDi6xYTUXY7kI/myiUNmYb1Cgr1EoQjfYai18Pkd9bvo4yHd0Mt82y9PaP18g97mHwF6iZI+u0rjA7pkeOYiWbxj76nswKU1jx3qdUQnFtEVOs3F9Squtat4ahXU+gPQFOFavqWXQGDfFGt++q1xPfjdoQhYJf4xl47KeghSaGOuL6wTq5a+g/GrnStDapToeBSipQSS7mr1MxL3HGw7BQkXmxzbEzhW9dJ1borYUPAnfw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
