conda_forge_output_validation: true
azure:
  store_build_artifacts: true
bot:
  automerge: true
github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  osx_arm64: osx_64
test_on_native_only: true
