azure:
  max_parallel: 20
bot:
  automerge: true
build_platform:
  linux_aarch64: linux_aarch64
  osx_arm64: osx_arm64
  osx_64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_64: github_actions
  linux_aarch64: github_actions
  osx_arm64: github_actions
  osx_64: azure
test: native_and_emulated
workflow_settings: 
  free_disk_space: quick
  pagefile_size: 10
  store_build_artifacts: true
  